# .yamllint.yml file
# See https://yamllint.readthedocs.io/en/stable/configuration.html for details

extends: default

rules:
  line-length:
    max: 140
    level: warning

  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  comments-indentation: disable

  document-start: disable

  key-duplicates: enable

  indentation:
    spaces: 2
    indent-sequences: whatever
    check-multi-line-strings: true

  empty-lines:
    max: 1
    max-end: 1
