# .yamllint.yml file
# See https://yamllint.readthedocs.io/en/stable/configuration.html for details

extends: default

rules:
  line-length:
    max: 100
    level: warning

  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  comments-indentation: disable

  document-start: disable

  key-duplicates: enable

  empty-lines:
    max: 1
    max-end: 1
