return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "html",
      "javascript",
      "json",
      "jsonc",
      "dockerfile",
      "diff",
      "lua",
      "luap",
      "luadoc",
      "markdown",
      "markdown_inline",
      "printf",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "xml",
      "vim",
      "vimdoc",
      "python",
      "yaml",
      "hcl",
      "terraform",
      "hyprlang",
      "helm",
      "rust",
      "make",
    },

    vim.treesitter.language.register("yaml", "ansible"),
  },
}
